site_name: tariff_fetch
site_description: This is a repository for modern data science projects.
site_author: Switchbox
repo_url: https://github.com/switchbox-data/tariff_fetch
repo_name: switchbox-data/tariff_fetch

nav:
  - Home: index.md
  - API Reference: modules.md

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
